### ISSUE TITLE
Add Travis-CI

### ISSUE THREAD

**Issue by stopyoukid** [Microsoft/charticulator-extensions#4]
Add travis-ci to do continuous integration.

**Comment by mrjamesperry** [comment]
Do you mean confidence interval, in a similar way to adding error bars in excel?  This would be excellent as this is sorely missed feature in PowerBi visuals.

**Comment by stopyoukid** [comment]
No it isn't, sorry.  I just updated the title to be more clear.  If you think that this would be a useful feature in general, it would be helpful if you created an issue on charticulator requesting the feature - https://github.com/Microsoft/charticulator/issues.
